CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_id BIGINT NOT NULL,
    type VARCHAR(64) NOT NULL,
    channel VARCHAR(16) NOT NULL,
    ref_type VARCHAR(64) NOT NULL,
    ref_id BIGINT NOT NULL,
    body VARCHAR(500) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    sent_at TIMESTAMP,
    failed_at TIMESTAMP,
    failure_reason VARCHAR(500),
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_notifications_idem UNIQUE (idempotency_key)
);

CREATE TABLE IF NOT EXISTS notification_outboxes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    processing_attempt INT NOT NULL,
    processing_lease_state VARCHAR(16) NOT NULL,
    processing_started_at TIMESTAMP,
    next_attempt_at TIMESTAMP,
    receiver_id BIGINT NOT NULL,
    channel VARCHAR(16) NOT NULL,
    body VARCHAR(500) NOT NULL,
    failure_reason VARCHAR(500),
    sent_at TIMESTAMP,
    failed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_notification_outboxes_notification UNIQUE (notification_id),
    CONSTRAINT uk_notification_outboxes_idem UNIQUE (idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_outbox_status_next_attempt
    ON notification_outboxes (status, next_attempt_at, id);
