CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_id BIGINT NOT NULL,
    type VARCHAR(64) NOT NULL,
    channel VARCHAR(16) NOT NULL,
    ref_type VARCHAR(64) NOT NULL,
    ref_id BIGINT NOT NULL,
    body VARCHAR(500) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    sent_at TIMESTAMP,
    failed_at TIMESTAMP,
    failure_reason VARCHAR(500),
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_notifications_idem UNIQUE (idempotency_key)
);
